import type { RSVPResponse } from "./types";

export const DEMO_MODE = process.env.DEMO_MODE === "true";

export const DEMO_RSVP_RESPONSES: RSVPResponse[] = [
  {
    id: "demo-1",
    full_name: "Emma Chen",
    attending: true,
    num_guests: 2,
    hotel_needed: true,
    hotel_check_in_dates: ["2027-01-23", "2027-01-24"],
    hotel_num_guests: 2,
    hotel_num_nights: 2,
    arrival_time: "12:00 – 2:00 PM",
    flight_number: "UA 857",
    flight_arrival_time: "11:30 AM",
    arriving_airport: "SFO",
    dietary_requirements: "Vegetarian",
    note_to_couple: "So excited! Can't wait to celebrate with you both.",
    created_at: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: "demo-2",
    full_name: "James Park",
    attending: true,
    num_guests: 1,
    hotel_needed: false,
    hotel_check_in_dates: [],
    hotel_num_guests: 1,
    hotel_num_nights: null,
    arrival_time: "2:00 – 4:00 PM",
    flight_number: "",
    flight_arrival_time: "",
    arriving_airport: "",
    dietary_requirements: "",
    note_to_couple: "",
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: "demo-3",
    full_name: "Sarah Williams",
    attending: false,
    num_guests: 1,
    hotel_needed: false,
    hotel_check_in_dates: [],
    hotel_num_guests: 1,
    hotel_num_nights: null,
    arrival_time: "",
    flight_number: "",
    flight_arrival_time: "",
    arriving_airport: "",
    dietary_requirements: "",
    note_to_couple: "Wishing you both a beautiful day. Sending love from London!",
    created_at: new Date().toISOString(),
  },
];
